name: nice_animals_flutter
description: A nice flutter application

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local libs
  shibe_api:
    path: ./local_libs/shibe_api

  photo_view: ^0.10.2
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  effective_dart: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/main_icon.png"
  adaptive_icon_background: '#ffffff'

flutter:
  uses-material-design: true

  assets:
    - assets/main_icon.png
    - assets/image_not_found.png
