name: shibe_api
description: Shibe api mappings
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.12.0